spring:
  application:
    name: Tech Poker
  messages:
      basename: messages
  thymeleaf:
    mode: HTML
---
spring:
  profiles: default
server:
  port: 8080
poker:
  external-url: http://localhost:8080
---
spring:
  profiles: heroku
poker:
  external-url: https://tech-poker.herokuapp.com
management:
  add-application-context-header: false
