spring:
  application:
    name: Tech Poker
  messages:
      basename: messages
  thymeleaf:
    mode: HTML
---
spring:
  profiles: default
server:
  port: 8080
poker:
  external-url: http://localhost:8080
---
spring:
  profiles: local-ssl
server:
  ssl:
    key-store: classpath:dev-only-keystore.p12
    key-store-password: changeit
    enabled: true
  port: 8443
poker:
  external-url: https://localhost:8443
---
spring:
  profiles: heroku
poker:
  external-url: https://tech-poker.herokuapp.com
management:
  server:
    add-application-context-header: false
