spring:
  application:
    name: Tech Poker
  messages:
      basename: messages
---
spring:
  profiles: default
server:
  port: 8080
poker:
  external-url: http://localhost:${server.port}
---
spring:
  profiles: openshift
poker:
  external-url: https://poker-demail.rhcloud.com
